name: Run ESLint
on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install --save-dev eslint
      - run: npm run lint
